server:
  port: ${PORT:0}
spring:
  application:
    name: wp-payroll

#  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false
#    discovery:
#      client:
#        simple:
#          instances:
#            wp-worker:
#              - host: localhost
#                port: 8080
#              - host: localhost
#                port: 8082

eureka:
  instances:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true

services:
  worker:
    url: http://localhost:8080/api/v1/worker