server:
  port: 8081
spring:
  application:
    name: wp-payroll
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    discovery:
      client:
        simple:
          instances:
            wp-worker:
              - host: localhost
                port: 8080
              - host: localhost
                port: 8082

services:
  worker:
    url: http://localhost:8080/api/v1/worker